### ISSUE TITLE
Todo/Task

### ISSUE THREAD

**Issue by Wekra** [Wekra/angry_nerds#22]
Create a page that represents one task/todo item.

**Comment by matthias-baeuerle** [comment]
Basic implementation done. We need to discuss how we present the switch in the detail screen to switch between notes (without status) and tasks (with status).

**Comment by matthias-baeuerle** [comment]
Description should be a text area.
Switch should be used (text "Task" on the left side, switch on the right)
Add swipe animation to delete todos (using `Dismissable`)

**Comment by Wekra** [comment]
see also: https://flutter.io/docs/cookbook/gestures/dismissible
