### ISSUE TITLE
Create Screens

### ISSUE THREAD

**Issue by tanipani** [Wekra/angry_nerds#7]
The following screens should be created: 

- [ ] Login
- [ ] Home 
- [ ] Notes (notes&tasks list )
- [x] Appointments (appointment list)
- [ ] Appoinment Detail View
- [ ] Orders and Parts (list)
- [ ] New Order
- [ ] Customers (customer list)
- [ ] Customer Detail View
- [ ] Service Product (details)
- [ ] Service Completion

![image](https://user-images.githubusercontent.com/20067647/47985747-ef795a00-e0da-11e8-9a02-e2dec6864cdf.png)

**Comment by matthias-baeuerle** [comment]
I guess it's better to open individual issues for each screen as we already did for some
